name: build-and-deploy

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour on the hour
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant write access for pushing changes

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use for authentication

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jinja2 feedparser arxiv google-generativeai tldextract beautifulsoup4

      - name: Run script to generate HTML
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python curation.py

      - name: Commit and push if it changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git add index.html || echo "No file to add"
          git commit -m "Update index.html with latest AI news" || echo "No changes to commit"
          git push || echo "No changes to push"
